language: python

python:
  - "2.7"

env:
  - DJANGO_VERSION=1.5

install:
  - pip install -q Django==$DJANGO_VERSION --use-mirrors
  - pip install -q south coverage
  - coverage run --source='.' manage.py test task

after_success:
  - coveralls
